// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOJSRCS7kfLa2iXFC6pzFT_K2TTtkCZA',
    appId: '1:1053547776012:web:18401168a1d1666e27c629',
    messagingSenderId: '1053547776012',
    projectId: 'fireprojek-a0279',
    authDomain: 'fireprojek-a0279.firebaseapp.com',
    storageBucket: 'fireprojek-a0279.firebasestorage.app',
    measurementId: 'G-XJQX8XK851',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvU-SGlg8onv-KEDveIGS-0yzdy56Y5dg',
    appId: '1:1053547776012:android:5ab0dadbe3e01ba927c629',
    messagingSenderId: '1053547776012',
    projectId: 'fireprojek-a0279',
    storageBucket: 'fireprojek-a0279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQnfz28oZ3lqQJUN9iEzyAR6o9zf5RMU',
    appId: '1:1053547776012:ios:dbc48c5c9833db9c27c629',
    messagingSenderId: '1053547776012',
    projectId: 'fireprojek-a0279',
    storageBucket: 'fireprojek-a0279.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQnfz28oZ3lqQJUN9iEzyAR6o9zf5RMU',
    appId: '1:1053547776012:ios:dbc48c5c9833db9c27c629',
    messagingSenderId: '1053547776012',
    projectId: 'fireprojek-a0279',
    storageBucket: 'fireprojek-a0279.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmOJSRCS7kfLa2iXFC6pzFT_K2TTtkCZA',
    appId: '1:1053547776012:web:7d3fbd471388106b27c629',
    messagingSenderId: '1053547776012',
    projectId: 'fireprojek-a0279',
    authDomain: 'fireprojek-a0279.firebaseapp.com',
    storageBucket: 'fireprojek-a0279.firebasestorage.app',
    measurementId: 'G-XHQD549KW3',
  );
}
